# Generated by Django 5.2.5 on 2025-08-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('travel_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('F', 'Flight'), ('T', 'Train'), ('B', 'Bus')], max_length=1)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.PositiveIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'source', 'destination', 'departure_time', 'price'], name='travel_opti_type_31bb03_idx')],
            },
        ),
    ]
