# Generated by Django 5.2.5 on 2025-08-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='UserIcon.png', upload_to='profile_images/'),
        ),
    ]
