# Generated by Django 5.2.5 on 2025-08-27 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel_options', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('X', 'Cancelled')], default='C', max_length=1)),
                ('travel_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_options.traveloption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'travel_option', 'booking_date', 'status'], name='bookings_bo_user_id_0e4457_idx')],
            },
        ),
    ]
